### ISSUE TITLE
Querying Potential Mistake

### ISSUE THREAD

**Issue by ghost** [paperbenni/bash#7]
Working on your `ngrok.sh` file over on my fork, when I noticed this line:

https://github.com/terminalforlife/bash/blob/master/ngrok/ngrok.sh#L54

In-case the numbers change, I'm referring to:

```bash
! [ -f ~/.ngrok2/ngrok.yml ] && rm ~/.ngrok2/ngrok.yml
```

See, it looks like you're checking for the non-existence of a file, then trying to remove it once you've confirmed it doesn't exist. The double-negative makes it confusing, I imagine. Did you meant to delete the file _if_ and only _if_ it's found?

**Comment by paperbenni** [comment]
Oh, I meant to check for its existence and then remove it. I copypasted the mkdir a few lines above and forgot to edit it properly, that's why it's there.

**Comment by ghost** [comment]
Ah, okidoke. Thanks for replying, I'll make the appropriate changes now, then send a PR.
